name: Github Actions 실행 시켜보기

on:
  push:
    branches:
      - main


# Workflow는 여러개의 Job으로 이루어 질 수 있고
jobs:
  My-Deploy-Job:
    runs-on : ubuntu-latest
  #하나의 작업은 여러 steps 로 구성 될 수 있다.
    steps:
      - name: Hello World 출력하기
        run: echo "Hello World"